version: "3"

services:
    db:
        image: postgres:15
        env_file:
            - ./.env
        volumes:
            - db_data:/var/lib/postgresql/data/

    web:
        build: ./
        ports:
            - 8000:8000
        depends_on:
            - db
        env_file:
            - ./.env

volumes:
    db_data:
