# Generated by Django 5.1.6 on 2025-03-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='exercise_needs',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='потребность в активности'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='friendliness',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='дружелюбность'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='название породы'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='shedding_amount',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='уровень линьки'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='trainability',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='обучаемость'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.PositiveIntegerField(verbose_name='возраст'),
        ),
    ]
